Repository dappforce/subsocial-parachain, pull requests merged in 2023-02, with the labels that each got.

#167 Move tests to corresponding pallets
  Cargo.lock
  Cargo.toml
  pallets/posts/tests/Cargo.toml
  pallets/posts/tests/src/comments_tests.rs
  pallets/posts/tests/src/lib.rs
  pallets/posts/tests/src/mock.rs
  pallets/posts/tests/src/post_tests.rs
  pallets/posts/tests/src/shared_posts_tests.rs
  pallets/posts/tests/src/tests_utils.rs
  pallets/reactions/tests/Cargo.toml
  pallets/reactions/tests/src/lib.rs
  pallets/reactions/tests/src/mock.rs
  pallets/reactions/tests/src/tests.rs
  pallets/reactions/tests/src/tests_utils.rs
  pallets/space-follows/tests/Cargo.toml
  pallets/space-follows/tests/src/lib.rs
  pallets/space-follows/tests/src/mock.rs
  pallets/space-follows/tests/src/tests.rs
  pallets/space-follows/tests/src/tests_utils.rs
  pallets/space-ownership/tests/Cargo.toml
  pallets/space-ownership/tests/src/lib.rs
  pallets/space-ownership/tests/src/mock.rs
  pallets/space-ownership/tests/src/tests.rs
  pallets/space-ownership/tests/src/tests_utils.rs
  pallets/spaces/tests/Cargo.toml
  pallets/spaces/tests/src/lib.rs
  pallets/spaces/tests/src/mock.rs
  pallets/spaces/tests/src/tests.rs
  pallets/spaces/tests/src/tests_utils.rs
Labels: help wanted, feature-release

#169 Add benchmarks to all pallets
  .maintain/weight-template.hbs
  Cargo.lock
  integration-tests/src/mock.rs
  integration-tests/src/utils/roles_utils.rs
  pallets/domains/src/benchmarking.rs
  pallets/domains/src/weights.rs
  pallets/posts/Cargo.toml
  pallets/posts/src/benchmarking.rs
  pallets/posts/src/lib.rs
  pallets/posts/src/weights.rs
  pallets/posts/tests/src/mock.rs
  pallets/posts/tests/src/tests_utils.rs
  pallets/reactions/Cargo.toml
  pallets/reactions/src/benchmarking.rs
  pallets/reactions/src/lib.rs
  pallets/reactions/src/weights.rs
  pallets/reactions/tests/src/mock.rs
  pallets/roles/Cargo.toml
  pallets/roles/src/benchmarking.rs
  pallets/roles/src/lib.rs
  pallets/roles/src/mock.rs
  pallets/roles/src/tests.rs
  pallets/roles/src/weights.rs
  pallets/space-follows/Cargo.toml
  pallets/space-follows/src/benchmarking.rs
  pallets/space-follows/src/lib.rs
  pallets/space-follows/src/weights.rs
  pallets/space-follows/tests/src/mock.rs
  pallets/space-ownership/Cargo.toml
  pallets/space-ownership/src/benchmarking.rs
  pallets/space-ownership/src/lib.rs
  pallets/space-ownership/src/weights.rs
  pallets/space-ownership/tests/src/mock.rs
  pallets/spaces/Cargo.toml
  pallets/spaces/src/benchmarking.rs
  pallets/spaces/src/lib.rs
  pallets/spaces/src/weights.rs
  pallets/spaces/tests/src/mock.rs
  pallets/spaces/tests/src/tests_utils.rs
  runtime/Cargo.toml
  runtime/src/lib.rs
Labels: feature-release

#109 Refactor CI to check and test code
  .github/workflows/test-code.yml
Labels: enhancement

#170 Add create space as profile feature
  Cargo.lock
  integration-tests/src/mock.rs
  integration-tests/src/tests/space_ownership.rs
  integration-tests/src/utils/spaces_utils.rs
  pallets/posts/src/benchmarking.rs
  pallets/posts/tests/src/mock.rs
  pallets/posts/tests/src/tests_utils.rs
  pallets/profiles/Cargo.toml
  pallets/profiles/src/benchmarking.rs
  pallets/profiles/src/lib.rs
  pallets/profiles/src/mock.rs
  pallets/profiles/src/tests.rs
  pallets/profiles/src/weights.rs
  pallets/reactions/src/benchmarking.rs
  pallets/reactions/tests/src/tests_utils.rs
  pallets/roles/src/benchmarking.rs
  pallets/space-follows/src/benchmarking.rs
  pallets/space-follows/tests/src/tests_utils.rs
  pallets/space-ownership/src/benchmarking.rs
  pallets/space-ownership/src/lib.rs
  pallets/space-ownership/tests/src/mock.rs
  pallets/space-ownership/tests/src/tests_utils.rs
  pallets/spaces/src/lib.rs
  pallets/spaces/tests/src/mock.rs
  pallets/spaces/tests/src/tests_utils.rs
  pallets/support/src/traits.rs
  pallets/support/src/traits/common.rs
  runtime/Cargo.toml
  runtime/src/lib.rs
Labels: feature-release

#175 Add SocialActionsProxy proxy type
  runtime/src/lib.rs
Labels: feature-release

#187 Refactor build docker GH Action
  .github/workflows/docker-build.yml
Labels: enhancement

#191 Fix secret name in "build docker" action
  .github/workflows/docker-build.yml
Labels: bug
